name: 'json extractorcs'

on:
  push:
    branches: [ master ]


    paths:
    - 'JsonFileExtractor.GitHubAction/**'               # run on all changes to this dir
    - '!JsonFileExtractor.GitHubAction/*.md' # ignore this file

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
 
    - name: dotnet-json-extractorcs
      id: dotnet-json-extractorcs
      uses: /chrisfactory/GithubActions@master
      with:
        path: .github/workflows/parameters/example.json
        properties: 'contentVersion;parameters.registryName'
        
    - name: Show properties 
      run: |
         echo ${{ steps.dotnet-json-extractorcs.outputs.json-values }}
        